### PR TITLE
API Typo + new Functionality

### PR DESCRIPTION
**Pull request by koglth**
Hi,

I have corrected a API typo and changed .Sucess to .Success and extended API with a ParentForm, so that the notifications can be displayed on the current Screen (not only Primary).

Thomas

### CODE REVIEW

**Comment by EVLF** [comment]
@leandrovip hello and thanks for your great work , can you make the alert don't take focus ?

**Comment by leandrovip** [comment]
Hi, I will test and implement the change
thanks 👍🏼👍🏼

**Comment by CArrandale** [comment]
Hello. Any update on this? All I'm trying to do it display the notifications top center of a form. Thank you.

**Comment by peros550** [comment]
Would it be possible to add  interval:"0" as an option so that notifications stay until they get closed by the user?

**Comment by koglth** [comment]
> Would it be possible to add interval:"0" as an option so that notifications stay until they get closed by the user?

Hi,
I have this function in my fork. 
There is an autoclose feature for every alert type.
https://github.com/koglth/Vip.Notification

**Comment by koglth** [comment]
> ## @leandrovip
> idk why when I used VIP.Notification from NuGet
> the alert take focus from other forms for some seconds and then return back
> , so got the src and I changed something to make it work
> i used this code: ........................... #endregion #region Windows API private const int SW_SHOWNOACTIVATE = 4; private const int HWND_TOPMOST = -1; private const uint SWP_NOACTIVATE = 0x0010;
> 
> ```
>     [DllImport("user32.dll", EntryPoint = "SetWindowPos")]
>     static extern bool SetWindowPos(
>      int hWnd,             // Window handle
>      int hWndInsertAfter,  // Placement-order handle
>      int X,                // Horizontal position
>      int Y,                // Vertical position
>      int cx,               // Width
>      int cy,               // Height
>      uint uFlags);         // Window positioning flags
> 
>     [DllImport("user32.dll")]
>     static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
> 
>     static void ShowInactiveTopmost(Form frm)
>     {
>         ShowWindow(frm.Handle, SW_SHOWNOACTIVATE);
>         SetWindowPos(frm.Handle.ToInt32(), HWND_TOPMOST,
>         frm.Left, frm.Top, frm.Width, frm.Height,
>         SWP_NOACTIVATE);
>     }
>     #endregion
>     private void FrmAlert_Load(object sender, EventArgs e)
>     {
>         //what work with me ↓
>         ShowInactiveTopmost(this);
>     }
> ```
> 
> ........................... **and again thanks for the great work**

Hi,

I have added you change to my

**Pull request closed without merging**
